name: Second Workflow
on: workflow_dispatch
jobs:
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print multiple commands
        run: |
          echo "first command"
          echo "second command"
